services:
  reverse-proxy:
    build:
      context: reverse_proxy
    ports:
      - "80:80"
    networks:
      - shared-network

  files_server:
    build:
      context: files_server
    volumes:
      - /Volumes/TheOther/Repositories/node_scrapper/catalog:/catalog
    networks:
      - shared-network

  client_server:
    build:
      context: client_server
    networks:
      - shared-network

networks:
  shared-network:

volumes:
  scrapper:
  catalog:
